// <auto-generated />
using System;
using ITHelpDeskApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITHelpDeskApp.Migrations
{
    [DbContext(typeof(HelpDeskContext))]
    partial class HelpDeskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ITHelpDeskApp.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 1L, 1);

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketNum")
                        .HasColumnType("int");

                    b.Property<string>("TicketTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            AssignedToUserId = 1,
                            ClosedDate = new DateTime(2023, 10, 24, 4, 6, 10, 402, DateTimeKind.Local).AddTicks(1906),
                            CreatedBy = "Alberta Crocodile",
                            CreatedDate = new DateTime(2023, 10, 17, 0, 29, 10, 402, DateTimeKind.Local).AddTicks(1878),
                            Priority = "Medium",
                            Status = "Closed",
                            TicketDescription = "The light on the tower turns on, but nothing ever shows up on the monitor. The monitor is on. Please help.",
                            TicketNum = 100,
                            TicketTitle = "Desktop won't turn on"
                        },
                        new
                        {
                            TicketId = 2,
                            AssignedToUserId = 2,
                            ClosedDate = new DateTime(2023, 10, 30, 2, 17, 10, 402, DateTimeKind.Local).AddTicks(1913),
                            CreatedBy = "John Doe",
                            CreatedDate = new DateTime(2023, 10, 28, 0, 29, 10, 402, DateTimeKind.Local).AddTicks(1911),
                            Priority = "Low",
                            Status = "Closed",
                            TicketDescription = "On Friday, I was able to connect to the Accounting server; however, now when I try to connect I receive a 'cannot connect to server' error message.",
                            TicketNum = 101,
                            TicketTitle = "Can't connect to internal Accounting server"
                        },
                        new
                        {
                            TicketId = 3,
                            AssignedToUserId = 2,
                            CreatedBy = "Alberta Crocodile",
                            CreatedDate = new DateTime(2023, 11, 18, 21, 56, 10, 402, DateTimeKind.Local).AddTicks(1916),
                            Priority = "High",
                            Status = "Open",
                            TicketDescription = "Receiving a '404 error' on every webpage. This is an urgent request.",
                            TicketNum = 101,
                            TicketTitle = "Can't connect to Internet"
                        },
                        new
                        {
                            TicketId = 4,
                            AssignedToUserId = 1,
                            CreatedBy = "John Doe",
                            CreatedDate = new DateTime(2023, 11, 17, 21, 29, 10, 402, DateTimeKind.Local).AddTicks(1919),
                            Priority = "Medium",
                            Status = "Open",
                            TicketDescription = "Hello, this is a request to purchase 2 licenses for Quickbooks Enterprise 2023. These licenses will be for the new hires starting next week.",
                            TicketNum = 101,
                            TicketTitle = "Request for new Quickbooks licenses"
                        });
                });

            modelBuilder.Entity("ITHelpDeskApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsItUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoggedInuser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Department = "IT",
                            FirstName = "Sally",
                            IsItUser = true,
                            IsLoggedInuser = false,
                            LastName = "Smith",
                            Password = "ItPassword1",
                            Username = "ItUser1"
                        },
                        new
                        {
                            UserId = 2,
                            Department = "IT",
                            FirstName = "Albert",
                            IsItUser = true,
                            IsLoggedInuser = false,
                            LastName = "Gator",
                            Password = "ItPassword2",
                            Username = "ItUser2"
                        },
                        new
                        {
                            UserId = 3,
                            Department = "Accounting",
                            FirstName = "John",
                            IsItUser = false,
                            IsLoggedInuser = false,
                            LastName = "Doe",
                            Password = "NonItPassword1",
                            Username = "NonItUser1"
                        },
                        new
                        {
                            UserId = 4,
                            Department = "Support",
                            FirstName = "Alberta",
                            IsItUser = false,
                            IsLoggedInuser = false,
                            LastName = "Crocodile",
                            Password = "NonItPassword2",
                            Username = "NonItUser2"
                        });
                });

            modelBuilder.Entity("ITHelpDeskApp.Models.Ticket", b =>
                {
                    b.HasOne("ITHelpDeskApp.Models.User", "AssignedToUser")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("ITHelpDeskApp.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
